### ISSUE TITLE
Exporting Tiles with Tiled

### ISSUE THREAD

**Issue by Shuutarou** [viciious/yatssd#1]
Whenever I try to export a tileset to a header file I get the following error: TypeError: Cannot call method 'toString' of undefined.

I get this error on both Linux and Windows versions of Tiled.

**Comment by viciious** [comment]
I need the tilemap to be able to reproduce the issue.

**Comment by Shuutarou** [comment]
OK, sorry to have bothered you. I figured out what was wrong. So the program I used to edit the tiles changed the color depth from 8bit to 32bit without my knowledge. Once I used an image editor to change it back to 8bit indexed, tile export worked as expected. Moral of the story, make sure your images are in 8bit indexed mode.
